# Generated by Django 3.1.5 on 2021-02-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='CEP',
            field=models.CharField(default='00.000-000', max_length=10),
        ),
    ]
