# Generated by Django 3.1.5 on 2021-03-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_address_cep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(default='endereço', max_length=200),
        ),
    ]
