# Generated by Django 3.1.5 on 2021-02-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(default='Agua', max_length=200)),
                ('drink_description', models.CharField(default='some description', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Drinks',
            },
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras_name', models.CharField(default='Nenhum', max_length=200)),
                ('extras_description', models.CharField(blank=True, default='Descriçao', max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='Pratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plates_name', models.CharField(default='sushi', max_length=200)),
                ('plates_amount', models.IntegerField(default=0)),
                ('plates_description', models.CharField(blank=True, default='nothing', max_length=300, null=True)),
                ('plates_types', models.CharField(choices=[('Sushi', 'sushi'), ('Sashimi', 'sashimi'), ('Temaki', 'temaki'), ('Hossomaki', 'hossomaki'), ('Niguiri', 'niguiri'), ('Gyuoza', 'gyoza'), ('Maki', 'maki')], default='Sushi', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Pratos',
            },
        ),
    ]
