# Generated by Django 3.1.5 on 2021-02-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_la_carte',
            fields=[
                ('pratos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Pedidos.pratos')),
                ('status', models.CharField(choices=[('PR', 'pedido realizado'), ('PA', 'pedido em andamento'), ('PP', 'pedido pronto'), ('PE', 'pedido entregue')], default='Esperando', max_length=100)),
            ],
            bases=('Pedidos.pratos',),
        ),
    ]
