# Generated by Django 3.1.5 on 2021-02-06 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Pedidos', '0002_a_la_carte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('bebidas', models.ManyToManyField(to='Pedidos.Drinks')),
                ('extras', models.ManyToManyField(to='Pedidos.Extras')),
                ('pratos', models.ManyToManyField(to='Pedidos.Pratos')),
            ],
        ),
        migrations.DeleteModel(
            name='A_la_carte',
        ),
    ]
