# Generated by Django 3.1.5 on 2021-02-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Pedidos', '0004_auto_20210206_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('ES', 'esperando pedido'), ('PR', 'pedido realizado'), ('PA', 'pedido em andamento'), ('PP', 'pedido pronto'), ('EA', 'entrega em andamento'), ('PE', 'pedido entregue')], default='Esperando', max_length=100),
        ),
        migrations.CreateModel(
            name='Rodizio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.pedido')),
            ],
            options={
                'verbose_name_plural': 'Rodizio',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.pedido')),
            ],
            options={
                'verbose_name_plural': 'Delivery',
            },
        ),
    ]
