# Generated by Django 3.1.5 on 2021-02-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_address_cep'),
        ('Pedidos', '0005_auto_20210206_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.ManyToManyField(to='management.Address'),
        ),
    ]
