# Generated by Django 3.1.5 on 2021-03-01 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pedidos', '0006_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bebidas',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pratos',
        ),
        migrations.RemoveField(
            model_name='rodizio',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='rodizio',
            name='plate',
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('entrega_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Pedidos.entrega')),
                ('Funçao', models.CharField(choices=[('CA', 'Carregador'), ('ODMD', 'Operador de Maquina de Descarregamento'), ('MC', 'Motorista de Caminhao')], max_length=50)),
            ],
            bases=('Pedidos.entrega',),
        ),
        migrations.DeleteModel(
            name='A_la_carte',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.DeleteModel(
            name='Extras',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Pratos',
        ),
        migrations.DeleteModel(
            name='Rodizio',
        ),
    ]
