# Generated by Django 3.1.5 on 2021-03-02 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0008_auto_20210301_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionarios',
        ),
    ]
