# Generated by Django 3.1.5 on 2021-03-02 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pedidos', '0009_delete_funcionarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='descarga',
        ),
        migrations.AddField(
            model_name='entrega',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
