# Generated by Django 3.1.5 on 2021-03-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0010_auto_20210302_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='descarga',
            field=models.CharField(choices=[('MEP', 'Maquinario Extremamente Pesado'), ('MP', 'Maqunario Pesado'), ('NN', 'Nao Necessita')], default='esperando', max_length=40),
        ),
        migrations.AddField(
            model_name='entrega',
            name='numero',
            field=models.CharField(default='000-000', max_length=20),
        ),
        migrations.AddField(
            model_name='entrega',
            name='objetos',
            field=models.CharField(choices=[('Pregos', 'pregos'), ('Canos de PVC', 'canos de pvc'), ('Fios de Cobre', 'fios de cobre'), ('Tabuas de Madeira', 'tabuas de madeira'), ('Massa de Revestimento', 'massa'), ('Cimento', 'cimento'), ('Tijolos', 'tijolos')], default='esperando', max_length=25),
        ),
        migrations.AddField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('ES', 'esperando pedido'), ('PR', 'pedido realizado'), ('PA', 'pedido em andamento'), ('EA', 'entrega em andamento'), ('PE', 'pedido entregue')], default='esperando', max_length=40),
        ),
    ]
