# Generated by Django 3.1.5 on 2021-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0013_auto_20210302_0103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionarios',
        ),
        migrations.AddField(
            model_name='entrega',
            name='Funçao',
            field=models.CharField(choices=[('CA', 'Carregador'), ('ODMD', 'Operador de Maquina de Descarregamento'), ('MC', 'Motorista de Caminhao')], default='nenhuma', max_length=50),
        ),
        migrations.AddField(
            model_name='entrega',
            name='matricula',
            field=models.CharField(default='000', max_length=30),
        ),
        migrations.AddField(
            model_name='entrega',
            name='nome',
            field=models.CharField(default='Arnaldao Sangue Bom', max_length=30),
        ),
    ]
