# Generated by Django 3.1.7 on 2021-03-02 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'verbose_name_plural': 'Entregas'},
        ),
        migrations.AddField(
            model_name='entrega',
            name='Funçao',
            field=models.CharField(choices=[('CA', 'Carregador'), ('ODMD', 'Operador de Maquina de Descarregamento'), ('MC', 'Motorista de Caminhao')], default='nenhuma', max_length=50),
        ),
        migrations.AddField(
            model_name='entrega',
            name='descarga',
            field=models.CharField(choices=[('MEP', 'Maquinario Extremamente Pesado'), ('MP', 'Maqunario Pesado'), ('NN', 'Nao Necessita')], default='esperando', max_length=40),
        ),
        migrations.AddField(
            model_name='entrega',
            name='matricula',
            field=models.CharField(default='000', max_length=30),
        ),
        migrations.AddField(
            model_name='entrega',
            name='nome',
            field=models.CharField(default='Arnaldao Sangue Bom', max_length=30),
        ),
        migrations.AddField(
            model_name='entrega',
            name='numero',
            field=models.CharField(default='000-000', max_length=20),
        ),
        migrations.AddField(
            model_name='entrega',
            name='objetos',
            field=models.CharField(choices=[('Pregos', 'pregos'), ('Canos de PVC', 'canos de pvc'), ('Fios de Cobre', 'fios de cobre'), ('Tabuas de Madeira', 'tabuas de madeira'), ('Massa de Revestimento', 'massa'), ('Cimento', 'cimento'), ('Tijolos', 'tijolos')], default='esperando', max_length=25),
        ),
        migrations.AddField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('ES', 'esperando pedido'), ('PR', 'pedido realizado'), ('PA', 'pedido em andamento'), ('EA', 'entrega em andamento'), ('PE', 'pedido entregue')], default='esperando', max_length=40),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
