# Generated by Django 3.1.7 on 2021-03-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210302_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='Funçao',
            field=models.CharField(choices=[('CA', 'Carregador'), ('ODMD', 'Operador de Maquina'), ('MC', 'Motorista de Caminhao')], default='nenhuma', max_length=50),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('PA', 'pedido aguardando'), ('EA', 'entrega em andamento'), ('E', 'entregue')], default='esperando', max_length=40),
        ),
    ]
