# Generated by Django 3.1.7 on 2021-03-02 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210302_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='Funçao',
            new_name='funçao',
        ),
        migrations.AddField(
            model_name='entrega',
            name='tempo',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
