# Generated by Django 3.1.5 on 2021-03-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210302_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='tempo',
        ),
    ]
