# Generated by Django 3.1.5 on 2021-03-03 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_entrega_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='tempo',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
