# Generated by Django 3.1.5 on 2021-03-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210304_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('Aguardando Pedido', 'pedido aguardando'), ('Entrega em Andamento', 'entrega em andamento'), ('Entregue', 'entregue')], default='esperando', max_length=40),
        ),
    ]
