# Generated by Django 3.1.7 on 2021-03-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210304_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='user',
        ),
    ]
