# Generated by Django 3.1.7 on 2021-03-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210307_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='Tipo_de_Entrega',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='marca_chassi',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='motor',
        ),
    ]
