# Generated by Django 3.1.7 on 2021-03-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_entrega_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='veiculo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.veiculo'),
        ),
    ]
