# Generated by Django 3.1.7 on 2021-03-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210307_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='produtos',
            field=models.ManyToManyField(to='main.Objeto'),
        ),
    ]
