# Generated by Django 3.1.7 on 2021-03-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_entrega_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='funcionarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.funcionario'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.veiculo'),
        ),
    ]
