# Generated by Django 3.1.7 on 2021-03-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210307_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='funcionarios',
        ),
        migrations.AddField(
            model_name='entrega',
            name='funcionarios',
            field=models.ManyToManyField(to='main.Funcionario'),
        ),
    ]
