# Generated by Django 3.1.7 on 2021-03-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210307_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='funçao',
            new_name='funcao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='matricula',
        ),
    ]
