# Generated by Django 3.1.7 on 2021-03-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210307_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
