# Generated by Django 3.1.7 on 2021-03-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_entrega_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
