# Generated by Django 3.1.7 on 2021-03-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210328_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='veiculos',
            field=models.ManyToManyField(to='main.Funcionario'),
        ),
    ]
