# Generated by Django 3.1.7 on 2021-03-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210328_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='funcinarios',
            field=models.ManyToManyField(to='main.Funcionario'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='veiculos',
            field=models.ManyToManyField(to='main.Veiculo'),
        ),
    ]
