# Generated by Django 3.1.7 on 2021-03-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210328_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='funcinarios',
            new_name='funcionarios',
        ),
    ]
