# Generated by Django 3.1.7 on 2021-03-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210328_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='produtos',
            field=models.ManyToManyField(to='main.Objeto'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade',
            field=models.IntegerField(default=0),
        ),
    ]
