# Generated by Django 3.1.7 on 2021-03-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210330_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='peso',
            field=models.IntegerField(default=0),
        ),
    ]
