# Generated by Django 3.1.7 on 2021-03-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_objeto_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='peso_total_carregado',
            field=models.IntegerField(default=0),
        ),
    ]
